dataset: &dataset 5-datasets
data_root: /data/Dataset/5-dataset
class_order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
              10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
              20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
              30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
              40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


total_cls_num: &total_cls_num 50
init_cls_num: &init_cls_num 10
inc_cls_num: &inc_cls_num 10
task_num: &task_num 5
image_size: &image_size 32

epoch: 1

batch_size: 10
testing_times: 1

optimizer:
  name: SGD
  kwargs:
    lr: 0.1

buffer:
  name: ERBuffer
  kwargs:
    capacity: 10000 # num_classes * M

backbone: 
  name: resnet18_AML
  kwargs:
    dataset: *dataset
    num_classes: *total_cls_num

classifier:
  name: ERAML
  kwargs:
    num_classes: *total_cls_num
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_free: True
    use_augs: False
    supcon_temperature: 0.2
    use_minimal_selection: False
