init_cls_num: &init_cls_num 5
inc_cls_num: &inc_cls_num 5
total_cls_num: &total_cls_num 100
task_num: &task_num 20
image_size: &image_size 224

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
epoch: 4 # 4
val_per_epoch: 4 # 4

train_batch_size: 128
test_batch_size: 64

setting: task-agnostic
testing_times: 1

train_trfms:
  - RandomResizedCrop :
      size: *image_size
      scale: [0.9, 1.0]
      interpolation: BICUBIC
  - ToTensor: {}
  - Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

test_trfms: 
  - Resize :
      size: *image_size
      interpolation: BICUBIC
  - ToTensor: {}
  - Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

optimizer:
  name: AdamW
  kwargs:
    lr: 1e-3
    weight_decay: 0.

lr_scheduler:
  name: CosineAnnealingWarmUp
  kwargs:
    T_max: 0 # Will be replaced in trainter.py with epoch * len(dataloader)
    warmup_length: 30

backbone:
  name: clip
  kwargs:
    model_name : ViT-B/16
    pretrained : True
    block_layer: ResidualAttentionBlock_MaskedMLP
    act_layer: QuickGELU
    norm_layer: LayerNorm

classifier:
  name: TRGP
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    label_smoothing: 0.
    prompt_template : "a bad photo of a {}."