
dataset: &dataset imagenet-r
data_root: /data/Dataset/imagenet-r

init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
total_cls_num: &total_cls_num 200
task_num: &task_num 10
image_size: &image_size 224

init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
task_num: *task_num

epoch: 1
val_per_epoch: 160
batch_size: 10

testing_times: 1

seed: 2

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 5e-4

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

backbone:
  name: resnet32_V2
  kwargs:
    num_classes: *total_cls_num
    args: 
      dataset: *dataset

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: LUCIR
  kwargs:
    num_class: *total_cls_num
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    feat_dim: 153664
    dist: 0.5
    lamda: 5
    K: 2
    lw_mr: 1
